#' bcbiosRNADataSet
#'
#' S4 class containing small RNA-seq counts and metadata generated by
#' [bcbio-nextgen](https://bcbio-nextgen.readthedocs.org/).
#'
#' [bcbiosRNADataSet] is a subclass of
#' [SummarizedExperiment::SummarizedExperiment] designed to store an RNA-seq
#' analysis.
#'
#'
#' The `metadata` accessor contains:
#'
#' - Sample summary statistics (a.k.a. metrics).
#' - Server run paths.
#' - R local environment information, including [sessionInfo()].
#'
#' @author Lorena Patano, Michael Steinbaugh
#' @rdname bcbiosRNADataSet
#' @examples
#' path <- system.file("extra", package="bcbiosRnaseq")
#' bcb <- load_run(file.path(path, "bcbio"))
#' @export
bcbiosRNADataSet <- setClass(  # nolint
    "bcbiosRNADataSet",
    contains = "SummarizedExperiment",
    representation = representation(callers = "SimpleList"))
setValidity("bcbiosRNADataSet", function(object) TRUE)
