#' bcbioSmallRnaDataSet
#'
#' S4 class containing small RNA-seq counts and metadata generated by
#' [bcbio-nextgen](https://bcbio-nextgen.readthedocs.org/).
#'
#' [bcbioSmallRnaDataSet] is a subclass of
#' [MultiAssayExperiment::MultiAssayExperiment] designed to store an RNA-seq
#' analysis.
#'
#'
#' The `metadata` accessor contains:
#'
#' - Sample summary statistics (a.k.a. metrics).
#' - Server run paths.
#' - R local environment information, including [sessionInfo()].
#'
#' @author Lorena Patano, Michael Steinbaugh
#' @rdname bcbioSmallRnaDataSet
#' @examples
#' path <- system.file("extra", package="bcbioSmallRna")
#' bcb <- load_run(file.path(path, "bcbio"))
#' @export
bcbioSRNADataSet <- setClass(  # nolint
    "bcbioSmallRnaDataSet",
    contains = "MultiAssayExperiment")
setValidity("bcbioSmallRnaDataSet", function(object) TRUE)
