#' bcbioSmallRnaDataSet
#'
#' S4 class containing small RNA-seq counts and metadata generated by
#' [bcbio-nextgen](https://bcbio-nextgen.readthedocs.org/).
#'
#' [bcbioSmallRnaDataSet] is a subclass of
#' [MultiAssayExperiment::MultiAssayExperiment] designed to store an RNA-seq
#' analysis.
#'
#'
#' The `metadata` accessor contains:
#'
#' - Sample summary statistics (a.k.a. metrics).
#' - Server run paths.
#' - R local environment information, including [sessionInfo()].
#'
#' @author Lorena Pantano, Michael Steinbaugh
#' @rdname bcbioSmallRnaDataSet
#' @export
bcbioSmallRnaDataSet <- setClass(  # nolint
    "bcbioSmallRnaDataSet",
    contains = "MultiAssayExperiment",
    slots = c(callers = "SimpleList"))
setValidity("bcbioSmallRnaDataSet", function(object) TRUE)
